# Generated by Django 4.2 on 2023-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name'), # used to count active users 
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersCount', models.IntegerField(default=0)),
                ('modelUsedCount', models.IntegerField(default=0)),
            ],
        ),
    ]
