# Generated by Django 4.2 on 2023-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
